version: '3.1'
services:
  # MySQL Service
  db:
    build: ./docker/db/
    container_name: some-db
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - some-network
    volumes:
      - ./.tmp/db-data:/var/lib/mysql

  # PHPMyAdmin service
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8001:80'
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
    networks:
      - some-network
# Docker Networks
networks:
  some-network:
    driver: bridge
